/* This file was generated by SableCC (http://www.sablecc.org/). */

package nonneumann.node;

import nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class TOperadoresAritmeticos extends Token
{
    public TOperadoresAritmeticos(String text)
    {
        setText(text);
    }

    public TOperadoresAritmeticos(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperadoresAritmeticos(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperadoresAritmeticos(this);
    }
}
